"use client";

import * as React from "react";
import { useReducedMotion } from "framer-motion";

import { Markdown } from "@/components/features/copilot/markdown-lite";

/** Reveals `text` character-by-character (typing effect), then swaps to
 * the fully-formatted Markdown render once done. Purely presentational -
 * the answer itself is already generated by the time this runs, this
 * just paces how it appears (Feature: "AI Shopping Advisor", requirement
 * "Typing effect while AI is generating advice"). */
export function TypingReveal({ text, speedMs = 10 }: { text: string; speedMs?: number }) {
  const reduce = useReducedMotion();
  const [shown, setShown] = React.useState(reduce ? text.length : 0);

  React.useEffect(() => {
    if (reduce) {
      setShown(text.length);
      return;
    }
    setShown(0);
    let i = 0;
    const step = Math.max(1, Math.round(text.length / 120)); // cap total frames for long answers
    const id = setInterval(() => {
      i += step;
      setShown(Math.min(text.length, i));
      if (i >= text.length) clearInterval(id);
    }, speedMs);
    return () => clearInterval(id);
  }, [text, speedMs, reduce]);

  const done = shown >= text.length;
  return done ? <Markdown text={text} /> : <p className="whitespace-pre-wrap">{text.slice(0, shown)}</p>;
}
