"""Shareable PDF evidence report generation (API_DOCUMENTATION.md §5).
Real, working PDF rendering via reportlab - not a stub. Stored through the
same `StorageProvider` used for community-report attachments (ADR-012),
so it inherits the local-disk/S3 swap for free.
"""

from __future__ import annotations

from io import BytesIO

from reportlab.lib import colors
from reportlab.lib.pagesizes import LETTER
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

from trustbuy_db.models import AgentRun, EvidenceItem, Investigation, Product, Recommendation, Seller

_VERDICT_COLORS = {
    "buy": colors.HexColor("#16a34a"),
    "buy_with_caution": colors.HexColor("#d97706"),
    "avoid_purchase": colors.HexColor("#dc2626"),
}
_VERDICT_LABELS = {"buy": "BUY", "buy_with_caution": "BUY WITH CAUTION", "avoid_purchase": "AVOID PURCHASE"}


def generate_investigation_report_pdf(
    *,
    investigation: Investigation,
    product: Product | None,
    seller: Seller | None,
    recommendation: Recommendation | None,
    evidence_items: list[EvidenceItem],
    agent_runs: list[AgentRun],
) -> bytes:
    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=LETTER, topMargin=0.75 * inch, bottomMargin=0.75 * inch)
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle("TrustBuyTitle", parent=styles["Title"], textColor=colors.HexColor("#1e293b"))
    heading_style = ParagraphStyle("TrustBuyHeading", parent=styles["Heading2"], spaceBefore=16)
    body_style = styles["BodyText"]

    story = [
        Paragraph("TrustBuy AI - Purchase Investigation Report", title_style),
        Spacer(1, 4),
        Paragraph(f"Source: {investigation.source_url}", body_style),
        Spacer(1, 12),
    ]

    if product:
        story.append(Paragraph(product.title, heading_style))
        price_line = (
            f"{product.currency} {product.current_price}" if product.current_price is not None else "Price unavailable"
        )
        story.append(Paragraph(price_line, body_style))
    if seller:
        story.append(Paragraph(f"Sold by: {seller.display_name or seller.external_seller_id}", body_style))

    if recommendation:
        verdict_color = _VERDICT_COLORS.get(recommendation.verdict, colors.black)
        verdict_style = ParagraphStyle(
            "Verdict", parent=styles["Heading1"], textColor=verdict_color, spaceBefore=20, spaceAfter=8
        )
        label = _VERDICT_LABELS.get(recommendation.verdict, recommendation.verdict.upper())
        story.append(Paragraph(f"{label} - {round(recommendation.confidence * 100)}% confidence", verdict_style))
        story.append(Paragraph(recommendation.explanation, body_style))
        story.append(
            Paragraph(
                f"<i>Model version: {recommendation.model_version} - explanation source: "
                f"{recommendation.explanation_source}</i>",
                styles["Italic"],
            )
        )

    story.append(Paragraph("Agent Summary", heading_style))
    agent_table_data = [["Agent", "Status", "Signal", "Confidence"]]
    for run in agent_runs:
        agent_table_data.append(
            [
                run.agent_name.replace("_", " ").title(),
                run.status,
                run.verdict_signal or "-",
                f"{round(run.confidence * 100)}%",
            ]
        )
    agent_table = Table(agent_table_data, colWidths=[1.8 * inch, 1.3 * inch, 1.5 * inch, 1 * inch])
    agent_table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#f1f5f9")),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#cbd5e1")),
                ("FONTSIZE", (0, 0), (-1, -1), 9),
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ]
        )
    )
    story.append(agent_table)

    story.append(Paragraph("Evidence Timeline", heading_style))
    if not evidence_items:
        story.append(Paragraph("No evidence was collected for this investigation.", body_style))
    for item in evidence_items:
        polarity_label = {"supports": "+", "contradicts": "-", "neutral": "o"}.get(item.polarity, "")
        story.append(Paragraph(f"[{polarity_label}] {item.summary}", body_style))
        story.append(Spacer(1, 4))

    story.append(Spacer(1, 20))
    story.append(
        Paragraph(
            "Generated by TrustBuy AI. This report is evidence-based guidance, not a guarantee - "
            "see the platform's Terms of Service for details.",
            styles["Italic"],
        )
    )

    doc.build(story)
    return buffer.getvalue()
